"""initial schema

Revision ID: 2f1ecee8db76
Revises: 
Create Date: 2026-02-27 07:00:15.833308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1ecee8db76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: processes.id is INTEGER PRIMARY KEY (implicitly NOT NULL in SQLite — no ALTER needed)
    op.drop_index('idx_process_number', table_name='processes')
    op.create_index(op.f('ix_processes_id'), 'processes', ['id'], unique=False)
    op.create_index(op.f('ix_processes_number'), 'processes', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processes_number'), table_name='processes')
    op.drop_index(op.f('ix_processes_id'), table_name='processes')
    op.create_index('idx_process_number', 'processes', ['number'], unique=1)
    # ### end Alembic commands ###
