name: prd

on:
  push:
    branches: ["production"]
  pull_request:
    branches: ["production"]

jobs:
  deploy:
    runs-on: [production226]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get current user
        run: whoami
      - name: run install, build and test
        run: |
          cd /opt/apps
          rm -rf consulta-de-processos
          git clone --branch production --single-branch git@github.com:PGM-CTEC/consulta-de-processos.git
          cd consulta-de-processos          
          rm .env
          cp .env.production .env
          chmod +x ./build.sh
          ./build.sh
